
db-list:
  - type: ""
    alias-name: ""
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
    disable: true
email:
  to: xxx@qq.com
  from: xxx@163.com
  host: smtp.163.com
  secret: xxx
  nickname: test
  port: 465
  is-ssl: true

jwt:
  signing-key: c6d39187-4b7e-497d-a259-bc89ccf80753
  expires-time: 7d
  buffer-time: 1d
  issuer: qmPlus
mysql:
  prefix: ""
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: qingyu
  username: admin
  password: 130561Cr
  path: chenrong.vip
  engine: ""
  log-mode: error
  max-idle-conns: 10
  max-open-conns: 100
  singular: false
  log-zap: false

redis:
  name: ""
  addr: chenrong.vip:6379
  password: 130561Cr@
  db: 0
  useCluster: false
  clusterAddrs:
    - 172.21.0.3:7000
    - 172.21.0.4:7001
    - 172.21.0.2:7002
system:
  db-type: mysql
  oss-type: local
  router-prefix: ""
  addr: 8888
  iplimit-count: 15000
  iplimit-time: 3600
  use-multipoint: false
  use-redis: false
  use-mongo: false
  use-strict-auth: false
zap:
  level: info
  prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  show-line: true
  log-in-console: true
  retention-day: -1
cors:
  mode: strict-whitelist
  whitelist:
    - allow-origin: example1.com
      allow-methods: POST, GET
      allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true
    - allow-origin: example2.com
      allow-methods: GET, POST
      allow-headers: content-type
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true
local:
  path: uploads/file
  store-path: uploads/file